# Generated by Django 5.2.7 on 2025-11-02 07:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_first_name", models.CharField(max_length=100)),
                ("applicant_last_name", models.CharField(max_length=100)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("applicant_phone", models.CharField(max_length=32)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("retired", "Retired"),
                        ],
                        default="employed",
                        max_length=20,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=150)),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount being financed before down payment.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid upfront to reduce the financed principal.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loan amount after deducting down payment.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Captured interest rate percentage from the financing term.",
                        max_digits=5,
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("has_valid_id", models.BooleanField(default=False)),
                ("has_proof_of_income", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financing_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_applications",
                        to="loans.financingterm",
                    ),
                ),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_applications",
                        to="inventory.motor",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("due", "Due"), ("paid", "Paid")],
                        default="due",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("loan_application", "sequence")},
            },
        ),
    ]
