# Generated by Django 5.2.7 on 2025-11-02 08:00

import django.core.validators
import django.db.models.deletion
import motofinai.apps.loans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loanapplication_paymentschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("valid_id", "Valid ID"),
                            ("proof_of_income", "Proof of income"),
                            ("other", "Other supporting document"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label to help staff identify the file.",
                        max_length=150,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=motofinai.apps.loans.models.loan_document_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="loans.loanapplication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_loan_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
