# Generated by Django 5.2.7 on 2025-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loandocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentschedule",
            name="status",
            field=models.CharField(
                choices=[("due", "Due"), ("overdue", "Overdue"), ("paid", "Paid")],
                default="due",
                max_length=10,
            ),
        ),
    ]
