# Generated by Django 5.1.4 on 2025-12-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loanapplication_custom_terms_and_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="credit_investigation_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="credit_investigation_notes",
            field=models.TextField(
                blank=True, help_text="Credit investigator's assessment and notes"
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="credit_investigator_approval",
            field=models.ForeignKey(
                blank=True,
                help_text="Credit Investigator who approved this loan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_investigated_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
