# Generated by Django 5.2.8 on 2025-12-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_loanapplication_credit_investigation_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="loanapplication",
            old_name="credit_investigation_at",
            new_name="second_approval_at",
        ),
        migrations.RemoveField(
            model_name="loanapplication",
            name="credit_investigation_notes",
        ),
        migrations.RemoveField(
            model_name="loanapplication",
            name="credit_investigator_approval",
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="second_approval_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Second approver (Finance Manager or Admin) who approved this loan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_approved_loan_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
