# Generated by Django 5.1.4 on 2025-12-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlogentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
            },
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="description",
            field=models.TextField(
                blank=True, help_text="Human-readable description of what happened"
            ),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="object_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary key of the object affected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="object_model",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Model name of the object affected",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Informational"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("critical", "Critical"),
                ],
                default="info",
                help_text="Severity level of the audit event",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("login_failed", "Failed Login Attempt"),
                    ("password_changed", "Password Changed"),
                    ("account_locked", "Account Locked"),
                    ("create", "Record Created"),
                    ("update", "Record Updated"),
                    ("delete", "Record Deleted"),
                    ("view", "Record Viewed"),
                    ("export", "Data Exported"),
                    ("import", "Data Imported"),
                    ("loan_created", "Loan Application Created"),
                    ("loan_approved", "Loan Approved"),
                    ("loan_rejected", "Loan Rejected"),
                    ("loan_disbursed", "Loan Disbursed"),
                    ("loan_completed", "Loan Completed"),
                    ("payment_recorded", "Payment Recorded"),
                    ("payment_reversed", "Payment Reversed"),
                    ("motor_received", "Motor Received"),
                    ("motor_inspected", "Motor Inspected"),
                    ("motor_approved", "Motor Approved"),
                    ("user_created", "User Created"),
                    ("user_modified", "User Modified"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_role_changed", "User Role Changed"),
                    ("system_config_changed", "System Configuration Changed"),
                    ("backup_created", "Backup Created"),
                    ("security_alert", "Security Alert"),
                ],
                db_index=True,
                default="view",
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional structured data about the event",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["-created_at"], name="audit_audit_created_06a422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["actor", "-created_at"], name="audit_audit_actor_i_55fb6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["action", "-created_at"], name="audit_audit_action_5a2cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["object_model", "object_id"],
                name="audit_audit_object__44e1e0_idx",
            ),
        ),
    ]
