# Generated by Django 5.1.4 on 2025-12-01 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("applicants", "All Applicants"),
                            ("approved_loans", "Approved Loans"),
                            ("released_motors", "Released Motors"),
                            ("ongoing_loans", "Ongoing Loans"),
                            ("motorcycle_status", "Motorcycle Status"),
                            ("payment_reconciliation", "Payment Reconciliation"),
                        ],
                        help_text="Type of report exported.",
                        max_length=50,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                        ],
                        help_text="Format the report was exported to.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the export.",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported file.",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Size of exported file in bytes.",
                        null=True,
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of data rows in the export.",
                        null=True,
                    ),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters that were applied when exporting.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if export failed."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the export was completed.",
                        null=True,
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("applicants", "All Applicants"),
                            ("approved_loans", "Approved Loans"),
                            ("released_motors", "Released Motors"),
                            ("ongoing_loans", "Ongoing Loans"),
                            ("motorcycle_status", "Motorcycle Status"),
                            ("payment_reconciliation", "Payment Reconciliation"),
                        ],
                        help_text="Type of report to generate.",
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("once", "One-time"),
                        ],
                        default="monthly",
                        help_text="How often to generate this report.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        help_text="Whether this scheduled report is active.",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_emails",
                    models.TextField(
                        help_text="Comma-separated list of email addresses to receive reports."
                    ),
                ),
                (
                    "include_charts",
                    models.BooleanField(
                        default=True,
                        help_text="Include charts and visualizations in the report.",
                    ),
                ),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this report was last generated.",
                        null=True,
                    ),
                ),
                (
                    "next_generation",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this report should be generated next.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
