# Generated by Django 5.1.4 on 2025-12-01 02:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0002_payment_bank_name_payment_bank_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POSSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cash float at session start.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "closing_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cash float at session end.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Session notes or discrepancies."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cashier who closed this session.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_pos_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        help_text="Cashier who opened this session.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_pos_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="POSTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="payment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        help_text="Payment being recorded.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_transaction",
                        to="payments.payment",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="POS session this transaction belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="pos.possession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        help_text="Sequential receipt number.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the receipt was printed.", null=True
                    ),
                ),
                (
                    "print_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this receipt was printed."
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        help_text="Payment this receipt is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_log",
                        to="payments.payment",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who printed this receipt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printed_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
