# Generated by Django 5.2.7 on 2025-11-02 03:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Motorcycle category (e.g. Scooter, Underbone).",
                        max_length=100,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=120, verbose_name="model")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("repossessed", "Repossessed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Motorcycle photo stored via configured media storage.",
                        null=True,
                        upload_to="inventory/motors/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["brand", "model_name", "year"],
                "unique_together": {("brand", "model_name", "year", "chassis_number")},
            },
        ),
    ]
