# Generated by Django 5.2.7 on 2025-11-17 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_motor_quantity'),
    ]

    operations = [
        # Drop the inventory_stock table if it already exists (from the old 0002_stock_motor_stock migration)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS inventory_stock;",
            reverse_sql="",  # No reverse operation needed
            state_operations=[],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=120, verbose_name='model')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('color', models.CharField(blank=True, max_length=50)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model_name', 'year', 'color'],
                'unique_together': {('brand', 'model_name', 'year', 'color')},
            },
        ),
        migrations.AddField(
            model_name='motor',
            name='stock',
            field=models.ForeignKey(blank=True, help_text='Stock batch this motor belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motors', to='inventory.stock'),
        ),
    ]
