# Generated by Django 5.1.4 on 2025-12-01 03:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_motor_approval_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorReceiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=120, verbose_name="model")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "vin_number",
                    models.CharField(
                        help_text="Vehicle Identification Number (VIN/Chassis Number)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True,
                        help_text="Engine/Motor number for identification",
                        max_length=100,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "motorcycle_type",
                    models.CharField(
                        choices=[
                            ("scooter", "Scooter"),
                            ("underbone", "Underbone"),
                            ("standard", "Standard"),
                            ("cruiser", "Cruiser"),
                            ("sport", "Sport"),
                            ("touring", "Touring"),
                            ("adventure", "Adventure"),
                            ("moped", "Moped"),
                            ("capping", "Capping"),
                            ("tricycle", "Tricycle"),
                        ],
                        default="scooter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Receipt"),
                            ("received", "Received"),
                            ("inspected", "Inspected"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost price from supplier",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("purchase_order_number", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Receipt"),
                            ("received", "Received"),
                            ("inspected", "Inspected"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Inspection status of the motor",
                        max_length=20,
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_motors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the inspection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_motors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_motors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("purchase_order", "Purchase Order"),
                            ("delivery_note", "Delivery Note"),
                            ("inspection_report", "Inspection Report"),
                            ("certificate", "Certificate/Title"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(
                        blank=True, null=True, upload_to="receiving_documents/%Y/%m/%d/"
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motor_receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="inventory.motorreceiving",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_receiving_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine_condition",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Engine condition assessment",
                        max_length=20,
                    ),
                ),
                (
                    "frame_condition",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Frame integrity assessment",
                        max_length=20,
                    ),
                ),
                (
                    "electrical_system",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Electrical components assessment",
                        max_length=20,
                    ),
                ),
                (
                    "tires_condition",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Tire condition assessment",
                        max_length=20,
                    ),
                ),
                (
                    "brakes_condition",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Brake system assessment",
                        max_length=20,
                    ),
                ),
                (
                    "paint_condition",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        help_text="Paint and body condition",
                        max_length=20,
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                ("issues_found", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("inspected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "motor_receiving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="inventory.motorreceiving",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="motorreceiving",
            index=models.Index(
                fields=["vin_number"], name="inventory_m_vin_num_0954aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="motorreceiving",
            index=models.Index(fields=["status"], name="inventory_m_status_d209c5_idx"),
        ),
        migrations.AddIndex(
            model_name="motorreceiving",
            index=models.Index(
                fields=["inspection_status"], name="inventory_m_inspect_a00d5c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="receivingdocument",
            unique_together={("motor_receiving", "document_type", "reference_number")},
        ),
    ]
