# Generated by Django 5.2.8 on 2025-12-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_motorreceiving_receivingdocument_receivinginspection_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="motor",
            unique_together={("brand", "model_name", "year")},
        ),
        migrations.RemoveField(
            model_name="motor",
            name="chassis_number",
        ),
    ]
