# Generated by Django 4.2.13 on 2025-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_motor_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motor",
            name="chassis_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle Identification Number (VIN/Chassis Number)",
                max_length=100,
            ),
        ),
    ]
