# Generated by Django 5.2.7 on 2025-11-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0004_alter_paymentschedule_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("base_score", models.PositiveIntegerField(default=30)),
                ("credit_score", models.PositiveIntegerField(default=650)),
                ("missed_payments", models.PositiveIntegerField(default=0)),
                ("employment_penalty", models.IntegerField(default=0)),
                ("income_factor", models.DecimalField(decimal_places=2, max_digits=6)),
                ("credit_factor", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "debt_to_income_ratio",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
