# Generated by Django 5.2.7 on 2025-11-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module name (e.g., 'motors', 'loan_applications', 'payments')",
                        max_length=100,
                    ),
                ),
                (
                    "record_id",
                    models.IntegerField(help_text="ID of the archived record"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional reason for archiving"
                    ),
                ),
                (
                    "data_snapshot",
                    models.JSONField(
                        help_text="Snapshot of the record at archive time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("archived", "Archived"), ("restored", "Restored")],
                        default="archived",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date archived"),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True, help_text="Date restored if applicable", null=True
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["module", "record_id"],
                        name="archive_arc_module_f771b6_idx",
                    ),
                    models.Index(
                        fields=["status"], name="archive_arc_status_e69ba7_idx"
                    ),
                ],
            },
        ),
    ]
