# Generated by Django 5.1.4 on 2025-12-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Bank name if payment method is bank transfer.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_reference",
            field=models.CharField(
                blank=True,
                help_text="Bank transaction reference if payment method is bank transfer.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="check_date",
            field=models.DateField(
                blank=True,
                help_text="Date on the check if payment method is check.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="check_number",
            field=models.CharField(
                blank=True,
                help_text="Check number if payment method is check.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("check", "Check"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("mobile_money", "Mobile Money"),
                    ("other", "Other"),
                ],
                default="cash",
                help_text="How the payment was received.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reconciled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this payment has been reconciled with bank statements.",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reconciled_at",
            field=models.DateTimeField(
                blank=True, help_text="When this payment was reconciled.", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who reconciled this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciled_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
